In [3]:
import numpy as np

print(np.version.version)

1.16.2


In [4]:
a = np.random.random((2,3,5))
print(a)

[[[0.75958506 0.64709275 0.75040953 0.25658842 0.32945783]
  [0.35410689 0.98124271 0.42169633 0.27596823 0.1254669 ]
  [0.40107662 0.40135483 0.47835205 0.86051948 0.52247597]]

 [[0.27811627 0.59721497 0.06990186 0.05064535 0.59252815]
  [0.43940812 0.9795526  0.1794428  0.74963283 0.50864852]
  [0.66888794 0.03156302 0.85491404 0.87325099 0.07219422]]]


In [5]:
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
a.size == b.size

True

In [7]:
print(np.add(a,b))
#not the same structure

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [8]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


In [89]:
#c = np.reshape(b,(2,3,5))
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [90]:
print(np.add(a,c))

[[[1.75958506 1.64709275 1.75040953 1.25658842 1.32945783]
  [1.35410689 1.98124271 1.42169633 1.27596823 1.1254669 ]
  [1.40107662 1.40135483 1.47835205 1.86051948 1.52247597]]

 [[1.27811627 1.59721497 1.06990186 1.05064535 1.59252815]
  [1.43940812 1.9795526  1.1794428  1.74963283 1.50864852]
  [1.66888794 1.03156302 1.85491404 1.87325099 1.07219422]]]


In [91]:
#10
d = a+c
print(d)

[[[1.75958506 1.64709275 1.75040953 1.25658842 1.32945783]
  [1.35410689 1.98124271 1.42169633 1.27596823 1.1254669 ]
  [1.40107662 1.40135483 1.47835205 1.86051948 1.52247597]]

 [[1.27811627 1.59721497 1.06990186 1.05064535 1.59252815]
  [1.43940812 1.9795526  1.1794428  1.74963283 1.50864852]
  [1.66888794 1.03156302 1.85491404 1.87325099 1.07219422]]]


In [92]:
#11
print(a)
print(d)

[[[0.75958506 0.64709275 0.75040953 0.25658842 0.32945783]
  [0.35410689 0.98124271 0.42169633 0.27596823 0.1254669 ]
  [0.40107662 0.40135483 0.47835205 0.86051948 0.52247597]]

 [[0.27811627 0.59721497 0.06990186 0.05064535 0.59252815]
  [0.43940812 0.9795526  0.1794428  0.74963283 0.50864852]
  [0.66888794 0.03156302 0.85491404 0.87325099 0.07219422]]]
[[[1.75958506 1.64709275 1.75040953 1.25658842 1.32945783]
  [1.35410689 1.98124271 1.42169633 1.27596823 1.1254669 ]
  [1.40107662 1.40135483 1.47835205 1.86051948 1.52247597]]

 [[1.27811627 1.59721497 1.06990186 1.05064535 1.59252815]
  [1.43940812 1.9795526  1.1794428  1.74963283 1.50864852]
  [1.66888794 1.03156302 1.85491404 1.87325099 1.07219422]]]


In [93]:
#12

e = np.multiply(a,c)
print(e)

[[[0.75958506 0.64709275 0.75040953 0.25658842 0.32945783]
  [0.35410689 0.98124271 0.42169633 0.27596823 0.1254669 ]
  [0.40107662 0.40135483 0.47835205 0.86051948 0.52247597]]

 [[0.27811627 0.59721497 0.06990186 0.05064535 0.59252815]
  [0.43940812 0.9795526  0.1794428  0.74963283 0.50864852]
  [0.66888794 0.03156302 0.85491404 0.87325099 0.07219422]]]


In [71]:
#13
(e == a).all()


True

In [45]:
#14
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9812427073484686
1.031563024600565
1.483709842157776


In [46]:
f = np.empty((2,3,5))
print(f)

[[[0.75958506 0.64709275 0.75040953 0.25658842 0.32945783]
  [0.35410689 0.98124271 0.42169633 0.27596823 0.1254669 ]
  [0.40107662 0.40135483 0.47835205 0.86051948 0.52247597]]

 [[0.27811627 0.59721497 0.06990186 0.05064535 0.59252815]
  [0.43940812 0.9795526  0.1794428  0.74963283 0.50864852]
  [0.66888794 0.03156302 0.85491404 0.87325099 0.07219422]]]


In [68]:
#16

f[np.where(d>d_min) and (d<d_mean)] = 25
f[np.where(d>d_mean) and (d<d_max)] = 75
f[np.where(d == d_mean)] = 50
f[np.where(d_min == d)] = 0
f[np.where(d_max == d)] = 100


In [69]:
#17
print(d)
print(f)

[[[1.75958506 1.64709275 1.75040953 1.25658842 1.32945783]
  [1.35410689 1.98124271 1.42169633 1.27596823 1.1254669 ]
  [1.40107662 1.40135483 1.47835205 1.86051948 1.52247597]]

 [[1.27811627 1.59721497 1.06990186 1.05064535 1.59252815]
  [1.43940812 1.9795526  1.1794428  1.74963283 1.50864852]
  [1.66888794 1.03156302 1.85491404 1.87325099 1.07219422]]]
[[[ 75.  75.  75.  75.  75.]
  [ 75. 100.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.   0.  75.  75.  75.]]]
